// ─────────────────────────────────────────────────────────────────────────────
// Terms of Service — single source of truth for the version string and the body
// shown on the /terms page and recorded against a user's acceptance at signup.
//
// User-facing rendering of the canonical draft in `legal/drafts/terms-of-service.md`;
// keep the two consistent. The legal draft is authoritative and still carries items
// for counsel (legal-entity/registration details, liability cap, governing venue,
// consumer-ADR contacts). The version carries a `-draft` suffix until counsel signs
// off (G2 / REMEDIATION-CHECKLIST Tier 0 §3.2). When the copy here changes, bump
// TERMS_VERSION so acceptance is re-prompted for the new version.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Current Terms version. Stored on `profiles.terms_version` when a user accepts at
 * signup, so we can detect (in future) that an older version was accepted and
 * re-prompt. Bump whenever the copy in <TermsOfServiceContent/> changes.
 */
export const TERMS_VERSION = "2026-07-13-draft";

/** Human-readable effective date, shown at the top of the terms body. */
export const TERMS_EFFECTIVE_DATE = "13 July 2026";

const CONTACT_EMAIL = "erik@eb-consulting.se";

/** The Terms of Service body — shared by the standalone /terms page. */
export function TermsOfServiceContent() {
  return (
    <div className="space-y-6 text-sm leading-relaxed text-foreground/80">
      <p className="text-foreground/60">
        Effective date: {TERMS_EFFECTIVE_DATE} · Version {TERMS_VERSION}
      </p>

      <p className="text-foreground/60">
        These Terms are provided in good faith and are being finalized with legal counsel;
        the version in force when you accept governs your use of the Service.
      </p>

      <p>
        <strong>Service:</strong> CLEAR — a self-serve B2B behavioral-analysis platform
        implementing the CLEAR Change Framework (Clarify → Leverage → Experiment → Analysis →
        Refinement).
        <br />
        <strong>Provider:</strong> CLEAR is operated by <strong>Erik Bohjort</strong> under the{" "}
        <strong>EB Consulting</strong> brand (eb-consulting.se); the contracting legal entity is{" "}
        <strong>Erik Bohjort Consulting AB</strong>, registered in <strong>Sweden (Täby)</strong>.
        <br />
        <strong>Contact:</strong>{" "}
        <a className="text-primary underline hover:no-underline" href={`mailto:${CONTACT_EMAIL}`}>
          {CONTACT_EMAIL}
        </a>
        .
      </p>

      <p>
        These Terms incorporate by reference the{" "}
        <a className="text-primary underline hover:no-underline" href="/refund">
          Refund &amp; Cancellation Policy
        </a>{" "}
        and the{" "}
        <a className="text-primary underline hover:no-underline" href="/privacy">
          Privacy Policy
        </a>
        , together with the Acceptable Use Policy and Data Processing Agreement (available on
        request), which form part of the agreement between you and CLEAR.
      </p>

      <Section title="1. Agreement and acceptance">
        <p>
          These Terms of Service (&ldquo;<strong>Terms</strong>&rdquo;) govern your access to and
          use of the CLEAR platform, websites, applications, APIs, and related services (the
          &ldquo;<strong>Service</strong>&rdquo;). By creating an account, accessing or using the
          Service, or by clicking to accept these Terms, you agree to be bound by them. If you do
          not agree, you must not use the Service.
        </p>
        <p>
          The Service is intended for <strong>business (B2B) use</strong>. By accepting, you
          represent that (a) you are at least 18 years old; (b) you are entering into these Terms
          on behalf of an organization; and (c) you have authority to bind that organization.
          &ldquo;You&rdquo; or &ldquo;Customer&rdquo; means both you and the organization you
          represent. A short note for anyone acting as a consumer appears in section 24.
        </p>
      </Section>

      <Section title="2. The Service">
        <p>
          CLEAR helps organizations diagnose and design behaviour-change interventions. You create
          a Project, enter a challenge brief, and upload supporting documents; an AI engine
          produces a structured analysis across the phases <strong>Clarify</strong> (measurable
          objectives), <strong>Leverage</strong> (systems maps and COM-B barrier analysis),{" "}
          <strong>Experiment</strong> (intervention candidates screened with APEASE),{" "}
          <strong>Analysis</strong>, and <strong>Refinement</strong>.
        </p>
        <p>
          <strong>AI engine.</strong> The analysis is generated by a third-party general-purpose
          AI model (Anthropic Claude) operated as a subprocessor on an inference-only basis.
          Customer inputs and outputs are <strong>not used to train AI models</strong>. An optional
          research agent may perform server-side web search/fetch. Certain analyses and reports are
          gated behind subscription tiers or one-off unlocks. We may modify, add, or remove
          features, and will not materially degrade the core functionality of a paid plan during a
          paid term without offering a remedy under section 22. Features marked
          &ldquo;beta&rdquo;/&ldquo;preview&rdquo; are provided &ldquo;as is&rdquo;.
        </p>
      </Section>

      <Section title="3. Accounts and workspaces">
        <p>
          You must provide accurate registration information and keep it current. The Account Owner
          creates a Workspace and may invite Authorized Users; the Customer is responsible for
          configuring access and for all activity under its Workspace and accounts. Keep
          credentials confidential and do not share accounts; notify us promptly at{" "}
          <a className="text-primary underline hover:no-underline" href={`mailto:${CONTACT_EMAIL}`}>
            {CONTACT_EMAIL}
          </a>{" "}
          of any suspected unauthorized access. A Project owner may invite Respondents via a
          tokenized link (no account; tokens expire after 30 days); the Customer is responsible for
          the lawful invitation of Respondents and collection of their contributions.
        </p>
      </Section>

      <Section title="4. Plans, billing, taxes, and renewal">
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <strong>Plans.</strong> Free, Solo, and Team subscription tiers, a one-off report
            unlock, and an Enterprise offering. Plan features, limits, and usage caps are described
            at the point of sale and in the Service. The Free tier is provided &ldquo;as is&rdquo;
            without warranties or a paid-support commitment and may change.
          </li>
          <li>
            <strong>Prices and currency.</strong> Prices are set in <strong>EUR</strong>. Final
            prices, inclusions, and any promotional terms are those displayed at purchase.
          </li>
          <li>
            <strong>Taxes and VAT.</strong> Applicable VAT and other taxes are calculated and shown
            at checkout (Stripe Tax); for consumers, prices are intended to be displayed
            VAT-inclusive. Where required, you must provide a valid VAT identification number and
            any information needed for correct tax treatment.
          </li>
          <li>
            <strong>Billing.</strong> Paid plans are billed through <strong>Stripe</strong>. Card
            data is handled solely by Stripe and never touches CLEAR servers. Subscriptions renew
            automatically at the then-current price unless cancelled before the end of the current
            period; cancellation takes effect at period end.
          </li>
          <li>
            <strong>Price changes.</strong> For a change affecting a recurring subscription, we
            give reasonable advance notice (for example, 30 days) before it takes effect at your
            next renewal; if you do not accept it, you may cancel before then.
          </li>
          <li>
            <strong>Refunds &amp; one-off unlocks.</strong> Delivery, withdrawal rights, refunds,
            billing errors, and chargebacks are governed by the{" "}
            <a className="text-primary underline hover:no-underline" href="/refund">
              Refund &amp; Cancellation Policy
            </a>
            .
          </li>
        </ul>
      </Section>

      <Section title="5. Customer data and intellectual property">
        <p>
          As between the parties, the <strong>Customer owns all Customer Data</strong>, including
          its inputs and the outputs generated for it; we claim no ownership. You grant CLEAR a
          limited, non-exclusive, worldwide, royalty-free licence to host, store, and process
          Customer Data solely to provide, secure, and support the Service, including transmitting
          relevant inputs to the AI subprocessor to generate outputs. Where the Service promotes
          research findings into a shared knowledge base, the relevant content is de-identified
          before promotion.
        </p>
        <p>
          CLEAR and its licensors own all right, title, and interest in the Service, including the
          platform software, the CLEAR Change Framework as implemented, prompts, templates,
          interfaces, documentation, and trademarks. You are responsible for your inputs and for
          having all necessary rights, consents, and lawful bases to submit them, including any
          third-party personal data. Where Customer Data contains personal data, processing is
          governed by the Data Processing Agreement: for project content and Respondent
          contributions the Customer is controller and CLEAR is processor; CLEAR is controller for
          account, authentication, billing, and website-analytics data.
        </p>
      </Section>

      <Section title="6. AI output disclaimer (important)">
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <strong>Decision-support only.</strong> Outputs are AI-generated decision-support. They
            are not professional, psychological, medical, clinical, financial, or legal advice, and
            do not create any professional or therapeutic relationship.
          </li>
          <li>
            <strong>No guaranteed outcomes.</strong> Outputs may be incomplete, inaccurate, or
            unsuitable, and AI systems can produce errors and &ldquo;hallucinations&rdquo;. We do
            not warrant any particular result or business outcome.
          </li>
          <li>
            <strong>Human judgement required.</strong> You must apply independent human judgement
            and appropriate professional review before acting on any output, and{" "}
            <strong>must not use outputs as the sole basis for any decision about an individual</strong>{" "}
            (including employment, health, legal status, credit, or access to services).
          </li>
          <li>
            <strong>Transparency.</strong> Consistent with Article 50 of the EU AI Act, you
            acknowledge that outputs are generated by an AI system, and you must ensure that
            Authorized Users and Respondents are informed that content is AI-generated where you
            share or act on it.
          </li>
        </ul>
      </Section>

      <Section title="7. Acceptable use">
        <p>
          Your use is subject to the Acceptable Use Policy (incorporated into these Terms). Without
          limitation, you must not upload special-category personal data or other people&rsquo;s
          personal data without a lawful basis and proper instruction, must not use outputs as the
          sole basis for decisions about individuals, and must not reverse-engineer, scrape,
          overload, or circumvent usage caps, paywalls, or security controls. You are responsible
          for ensuring that Respondent and third-party data are collected and provided lawfully.
        </p>
      </Section>

      <Section title="8. Third-party services">
        <p>
          The Service relies on third-party subprocessors (for example, Supabase for hosting,
          Anthropic for AI inference, Stripe for payments, Brevo for transactional email; and, on
          the marketing site only, Google Analytics/Ads and Microsoft Bookings). Your use may be
          subject to those providers&rsquo; terms. We are not responsible for third-party services
          we do not control, and their availability may affect the Service. Subprocessor details
          and transfer bases are set out in the Data Processing Agreement.
        </p>
      </Section>

      <Section title="9. Confidentiality">
        <p>
          Each party will use the other&rsquo;s non-public information only to perform under these
          Terms, protect it with at least reasonable care, and not disclose it except to personnel
          and contractors bound by confidentiality obligations. This does not apply to information
          that is or becomes public without breach, was lawfully known without obligation, is
          independently developed, or is rightfully received from a third party; disclosure
          required by law is permitted with prior notice where lawful.
        </p>
      </Section>

      <Section title="10. Warranties and disclaimers">
        <p>
          Except as expressly stated and to the maximum extent permitted by applicable law, the
          <strong> Service and all outputs are provided &ldquo;AS IS&rdquo; and &ldquo;AS
          AVAILABLE&rdquo;</strong>, and CLEAR disclaims all warranties, express or implied,
          including merchantability, fitness for a particular purpose, satisfactory quality,
          accuracy, and non-infringement. We do not warrant that the Service will be uninterrupted,
          error-free, or secure, or that outputs will be accurate or fit for any purpose. Nothing
          here excludes any warranty or right that cannot be excluded under applicable mandatory law
          (including EU/Swedish consumer law where it applies — see section 24).
        </p>
      </Section>

      <Section title="11. Limitation of liability">
        <p>
          To the maximum extent permitted by law, neither party is liable for indirect, incidental,
          special, consequential, or punitive damages, or for loss of profits, revenue, goodwill,
          anticipated savings, or data. CLEAR&rsquo;s total aggregate liability arising out of or
          relating to these Terms or the Service will not exceed the greater of (a) the fees paid or
          payable by you to CLEAR in the 12 months preceding the event giving rise to the claim, or
          (b) EUR 100. Nothing limits liability that cannot be limited under mandatory law,
          including for death or personal injury caused by negligence, fraud, or wilful misconduct,
          and these limits do not affect the non-excludable rights of any consumer (section 24).
        </p>
      </Section>

      <Section title="12. Indemnity">
        <p>
          To the extent permitted by law, you will defend, indemnify, and hold harmless CLEAR and
          its personnel against third-party claims, damages, losses, and reasonable costs arising
          out of: your inputs or Customer Data; your use of the Service or outputs in breach of
          these Terms, the Acceptable Use Policy, or applicable law; your collection or submission
          of personal data without a lawful basis; or decisions or actions you take based on
          outputs. This does not apply to the extent a claim arises from CLEAR&rsquo;s breach, and
          is subject to any non-excludable consumer rights (section 24).
        </p>
      </Section>

      <Section title="13. Suspension">
        <p>
          We may suspend or restrict access, immediately and without liability, where reasonably
          necessary to prevent material harm, address a security risk or violation of the Acceptable
          Use Policy or law, or address overdue fees after notice. Where practicable and lawful, we
          give notice and an opportunity to remedy, and restore access once the cause is resolved.
        </p>
      </Section>

      <Section title="14. Term and termination">
        <p>
          These Terms apply for as long as you have an account or use the Service. You may stop
          using the Service and cancel any subscription at any time as described in the Refund &amp;
          Cancellation Policy, and may close your account by contacting support. We may suspend or
          terminate for material breach not cured within 30 days of notice (or immediately for
          breaches incapable of cure or serious violations), if required by law, or on
          discontinuation of the Service with reasonable notice.
        </p>
        <p>
          On termination your right to access the Service ceases and you remain liable for accrued
          fees. Before or promptly after termination you may export your Customer Data; afterwards
          CLEAR deletes or de-identifies Customer Data per the retention periods in the Privacy
          Policy (account and project data deleted within 30 days of account closure; backups
          purged within 90 days), except where retention is required by law (billing/accounting
          records retained 7 years under the Swedish Bookkeeping Act).
        </p>
      </Section>

      <Section title="15. Compliance, force majeure, and publicity">
        <p>
          Each party will comply with applicable laws, including export controls and sanctions.
          Neither party is liable for failures or delays (other than payment obligations) caused by
          events beyond its reasonable control. Neither party will use the other&rsquo;s name or
          marks without prior consent, except that CLEAR may identify you as a customer in customer
          lists with your prior consent.
        </p>
      </Section>

      <Section title="16. Governing law and disputes">
        <p>
          These Terms are governed by the laws of <strong>Sweden</strong>, excluding its
          conflict-of-laws rules and the UN Convention on Contracts for the International Sale of
          Goods (CISG). Subject to section 24, the parties submit to the exclusive jurisdiction of
          the courts of Sweden (Stockholm District Court as court of first instance). These Terms
          are written for the EU/EEA.
        </p>
      </Section>

      <Section title="17. Changes to the Service and to these Terms">
        <p>
          We may amend these Terms from time to time. For material changes affecting paid plans, we
          give reasonable advance notice (for example, 30 days) by email or in-app before they take
          effect. Your continued use after the effective date constitutes acceptance; if you do not
          agree to a material change, you may cancel before it takes effect, in which case the prior
          Terms govern until the end of your current paid period.
        </p>
      </Section>

      <Section title="18. Miscellaneous">
        <p>
          These Terms, together with the documents they incorporate and any Enterprise Agreement,
          are the entire agreement regarding the Service. In case of conflict the order of
          precedence is: an executed Enterprise Agreement; the Data Processing Agreement (for
          personal-data matters); these Terms; then the other incorporated policies. You may not
          assign these Terms without our consent; we may assign to an affiliate or in a
          merger/acquisition on notice. If any provision is unenforceable it is modified to the
          minimum extent necessary and the rest remains in effect. Failure to enforce is not a
          waiver. Notices to CLEAR go to{" "}
          <a className="text-primary underline hover:no-underline" href={`mailto:${CONTACT_EMAIL}`}>
            {CONTACT_EMAIL}
          </a>
          ; notices to you may be sent to your account email or posted in the Service. These Terms
          are provided in English.
        </p>
      </Section>

      <Section title="19. Note for consumers (EU)">
        <p>
          These Terms are designed for business (B2B) use. If, despite section 1, you use the
          Service as a consumer and mandatory EU/EEA or Swedish consumer-protection law applies:
        </p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Nothing here limits your non-waivable statutory rights, including conformity rights and protection against unfair contract terms.</li>
          <li>You may have a 14-day right of withdrawal for distance contracts, subject to the digital-content rules in the Refund &amp; Cancellation Policy.</li>
          <li>Mandatory consumer law of your country of residence may apply regardless of the governing-law clause, and you may bring proceedings in your local courts where the law so provides.</li>
          <li>
            You may use the EU Online Dispute Resolution platform
            (ec.europa.eu/consumers/odr) and may have access to an out-of-court dispute body such
            as the Swedish National Board for Consumer Disputes (Allmänna reklamationsnämnden, ARN).
          </li>
        </ul>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h3 className="font-semibold text-foreground">{title}</h3>
      {children}
    </section>
  );
}
